base_dir: '' # Path to Base Directory
superpoint_model_path: 'models/points_model.pth' # Path to SuperPoint Model
data:
    normal_size: [480, 640] # min_size, max_size
model:
  superpoint:
    cell : 8
    detection_threshold: 0.2
    batch_size: 1