base_dir: './youtube-vis/train' # YT-VIS Train directory
videos: './AirObject/splits/ytvis_train_train.txt' # YT-VIS Training Videos List
log_dir: './experiments/train_seqnet' # Logging directory
netvlad_model_path: './models/netvlad_model.pth' # YT-VIS Finetuned NetVLAD Model path
resume: False
seqnet_model_path: ''
sum_iter: 
optimizer_path: ''
model:
  netvlad:
    descriptor_dim: 256
    vlad_numc: 32
  seqnet:
    encoder_dim: 8192
    out_dim: 4096
    kernel_size: 1
    train:
      seqlen: 4
      batch_size: 16
      positive_margin: 1
      negative_margin: 0.2
      lambda_d: 1
      epochs: 15
      lr: 0.0001
      checkpoint: 500